# Generated by Django 5.1.2 on 2024-10-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockprice",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
