# Generated by Django 4.2.16 on 2024-10-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('symbol', 'date')},
        ),
    ]
