# Generated by Django 4.2.16 on 2024-10-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stockprice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprediction',
            unique_together={('symbol', 'date')},
        ),
    ]
