# Generated by Django 5.1.2 on 2024-10-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_stockprediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockprediction",
            name="actual_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
